name: Build & Push container image
on: [push]
jobs:
  Build-Image-and-Push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Container Image
        run: docker build ./app -t ghcr.io/${{ github.repository_owner }}/liatrio-app-${{ github.ref_name }}:latest
      
      - name: Login to ghcr.io
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Push image
        run: docker push ghcr.io/${{ github.repository_owner }}/liatrio-app-${{ github.ref_name }}:latest
      